apiVersion: v1
kind: ReplicationController
metadata:
  name: tugas
spec:
  replicas: 3
  selector:
      app: tugas
  template:
    metadata:
      labels:
        app: tugas
    spec:
      containers:
      - name: httpd
        image: dockondokondo/httpd:v2
        ports:
        - containerPort: 80